# Generated by Django 4.2.7 on 2023-11-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tasks_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
    ]
