# Generated by Django 4.2.7 on 2023-11-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tasks_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='dateTimeDone',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
