# Generated by Django 4.2.7 on 2023-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tasks_datetimedone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dateTimeDone',
            field=models.DateTimeField(null=True),
        ),
    ]
